### ISSUE TITLE
TypeError when running latest version of SIMIM

### ISSUE THREAD

**Issue by tg137** [nismod/simim#17]
### Package versions
* microsimulation - Latest from GitHub
* ukpopulation - Latest from GitHub
* SIMIM - Latest from GitHub

### Error
When running `python scripts/run.py -c config/production2.json`, the following error is produced:
```
Traceback (most recent call last):
  File "/code/simim/scripts/run.py", line 34, in <module>
    main(params)
  File "/code/simim/scripts/run.py", line 24, in main
    simim.simim(params)
  File "/opt/conda/envs/simim/lib/python3.6/site-packages/simim-1.0.0-py3.6.egg/simim/simim.py", line 106, in simim
  File "/opt/conda/envs/simim/lib/python3.6/site-packages/simim-1.0.0-py3.6.egg/simim/data_apis.py", line 89, in get_people
TypeError: '<' not supported between instances of 'int' and 'str'
```

### Potential Fix
Change https://github.com/nismod/simim/blob/73a97f96db81d3418899ad66e9f5aa4b1c6cc977/simim/data_apis.py#L89 to be:
`if year < int(self.snpp.min_year(country)):`

and also https://github.com/nismod/simim/blob/73a97f96db81d3418899ad66e9f5aa4b1c6cc977/simim/data_apis.py#L91 to be:
`elif year <= int(self.snpp.max_year(country))`

This fix works for my installation.

**Comment by virgesmith** [comment]
caused by using an old version of ukpopulation. 1.1.3 is the minimum (as specified in requirements.txt)
